// <auto-generated />
using System;
using App.Infraestructure.Connect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infraestructure.Connect.Migrations
{
    [DbContext(typeof(ConnectContext))]
    partial class ConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Infraestructure.Connect.Entities.Exception_LogEntities", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Aplicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<string>("ExceptionString")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("FechaLog")
                        .HasColumnType("Datetime");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.HasKey("LogId");

                    b.ToTable("Exception_Log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
